import { execSync } from "node:child_process";
import { readFileSync, readdirSync, writeFileSync, rmSync, mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const VERSION = process.argv[2] || "latest";
const work = mkdtempSync(join(tmpdir(), "mpga-icons-"));
execSync(`npm pack lucide-static@${VERSION} --pack-destination ${work}`, { stdio: "ignore" });
const tgz = readdirSync(work).find((f) => f.endsWith(".tgz"));
execSync(`tar xzf ${join(work, tgz)} -C ${work} package/icons package/package.json`, {
  stdio: "ignore",
});

const meta = JSON.parse(readFileSync(join(work, "package/package.json"), "utf8"));
const dir = join(work, "package/icons");
const icons = {};
for (const f of readdirSync(dir).sort()) {
  if (!f.endsWith(".svg")) continue;
  const body = readFileSync(join(dir, f), "utf8")
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>[\s\S]*$/, "")
    .replace(/\s+/g, " ")
    .trim();
  icons[f.slice(0, -4)] = body;
}

const out = `// generated by tools/gen-icons.mjs from lucide-static@${meta.version} (ISC)
window.MPGA_ICONS = ${JSON.stringify(icons)};
window.MPGA_ICONS_VERSION = ${JSON.stringify(meta.version)};
`;
writeFileSync("src/engine/icons.js", out);
rmSync(work, { recursive: true, force: true });
console.log(
  `icons: ${Object.keys(icons).length}, lucide-static ${meta.version}, ${(out.length / 1024) | 0} KB`,
);
